
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Frame1 extends javax.swing.JFrame {

    String temp="";
    Double berat, tinggi, h1;
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Hasil = new javax.swing.JTextField();
        Ideal = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Laki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Tinggi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Saran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Hasil.setEditable(false);
        Hasil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Hasil);
        Hasil.setBounds(10, 350, 420, 30);

        Ideal.setEditable(false);
        Ideal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Ideal);
        Ideal.setBounds(250, 270, 50, 30);

        Berat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Berat);
        Berat.setBounds(170, 140, 50, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 270, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 10, 190, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("kg");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 270, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tinggi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 100, 90, 30);

        buttonGroup1.add(Laki);
        Laki.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Laki.setText("Laki - Laki");
        getContentPane().add(Laki);
        Laki.setBounds(170, 180, 90, 30);

        buttonGroup1.add(Perempuan);
        Perempuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Perempuan.setText("Perempuan");
        getContentPane().add(Perempuan);
        Perempuan.setBounds(280, 180, 100, 30);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 220, 80, 30);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 220, 80, 30);

        jButton3.setText("Coba Lagi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 220, 100, 30);

        Tinggi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Tinggi);
        Tinggi.setBounds(170, 100, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 310, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("cm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 140, 90, 30);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Nama);
        Nama.setBounds(170, 60, 150, 30);

        Saran.setEditable(false);
        Saran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Saran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Saran);
        Saran.setBounds(10, 390, 420, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 180, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Nama");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 60, 90, 30);

        setBounds(0, 0, 451, 467);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Nama.getText().equals("")||Berat.getText().equals("")||Tinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data Masukan Harus Diisi Semua");
        }else if (Laki.isSelected()||Perempuan.isSelected()){
            try{
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Inputan Salah");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Radio Button Belum Dipilih");
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Berat.setText("");
        Tinggi.setText("");
        Hasil.setText("");
        Saran.setText("");
        Ideal.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField Ideal;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JTextField Saran;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        tinggi = Double.valueOf(Tinggi.getText());
        berat = Double.valueOf(Berat.getText());
    
        if (Laki.isSelected()){
            h1 = (tinggi - 100) * 1;
        }else if(Perempuan.isSelected()){
            h1 = (tinggi - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if(h1 < berat){
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText() + ", Sepertinya anda Overweight :( ");
            Saran.setText("Banyaklah berolahraga dan hindari makanan yang berkarbohidrat");
        }else if(h1 > berat){
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText() + ", Sepertinya anda Underweight :( ");
            Saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else{
            Ideal.setText(temp);
            Hasil.setText("Selamat " + Nama.getText() + ", Berat badan anda ideal :) ");
            Saran.setText("Lanjutkan pola makan dan hidup sehat :)");
        }
    }
}
